modLoader="javafml"
loaderVersion="${fmlRange}"
license="GPL 3.0"
issueTrackerURL="https://github.com/ldtteam/structurize/issues/new/choose"
[[mods]]
modId="structurize"
version="${file.jarVersion}" #mandatory
displayName="Structurize"
displayURL="https://minecolonies.com/"
logoFile="structurize.png"
credits="Every coffee anyone ever drank!"
authors="LDT Team"
description='''
An astonishing way to copy & paste structures!

Allows you to:
 - save structures of your choice into a file of small size
 - load them back and place them anywhere anytime
 - create various shapes using math formulas
 - and many other nice things a great builder would love to have!
'''
[[dependencies.structurize]]
    modId="neoforge"
    type="required"
    versionRange="${forgeRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.structurize]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftRange}"
    ordering="NONE"
    side="BOTH"
[[dependencies.structurize]]
    modId="blockui"
    type="required"
    versionRange="${blockUiRange}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.structurize]]
    modId="domum_ornamentum"
    type="required"
    versionRange="${domumOrnamentumRange}"
    ordering="AFTER"
    side="BOTH"
