blank_issues_enabled: false
contact_links:
  - name: Support Requests and Anything Else Discussions
    about: Visit our discord
    url: https://discord.minecolonies.com
  - name: Minecolonies Bug Tracker
    about: Please follow the given template
    url: https://github.com/ldtteam/minecolonies/issues/new/choose
  - name: Minecolonies Feature/Change Tracker
    about: Please follow the given template
    url: https://github.com/ldtteam/minecolonies-features/issues/new/choose
