blank_issues_enabled: false
contact_links:
  - name: Minecolonies Bug Tracker
    about: 
    url: https://github.com/ldtteam/minecolonies/issues/new/choose
  - name: Minecolonies Feature/Change Tracker
    about: 
    url: https://github.com/ldtteam/minecolonies-features/issues/new/choose
