name: Release 1.21.1

on:
  push:
    branches: [
      "version/1.21",
      "release/1.21",
      "testing/1.21",
    ]

permissions:
  contents: write
  statuses: write

jobs:
  release:
    uses: ldtteam/operapublicacreator/.github/workflows/gradle.publish.yaml@ng7
    with:
      java: 21
      curse_release_type: ${{ contains(github.ref, 'release') && 'release' || 'beta' }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
      CURSE_API_KEY: ${{ secrets.CURSE_API_KEY }}
      GRADLE_ENCRYPTION_KEY: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
